import type { Metadata } from 'next';
import './globals.css';
import AuthProvider from '@/components/AuthProvider';
import { CartProvider } from '../context/CartContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  // eslint-disable-next-line no-undef
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <CartProvider>
          <AuthProvider>{children}</AuthProvider>{' '}
        </CartProvider>
      </body>
    </html>
  );
}
